; Auto-generated by make_atr.py - DO NOT EDIT
sky_sec_lo
        dta 161
        dta 78
        dta 228
        dta 136
        dta 243
        dta 60
        dta 227
        dta 68
        dta 214
sky_sec_hi
        dta 9
        dta 10
        dta 10
        dta 11
        dta 11
        dta 12
        dta 12
        dta 13
        dta 13
sky_sec_cnt
        dta 173
        dta 150
        dta 164
        dta 107
        dta 73
        dta 167
        dta 97
        dta 146
        dta 179
