#!/usr/bin/env python3
"""
Create bootable ATR disk image for DOOM2D.
Layout: boot loader (sectors 1-3) + XEX (sectors 4+) + level data

Usage:
    python make_atr.py output.atr boot.bin doom2d.xex level1.lvl [level2.lvl ...]
"""

import sys
import os
import struct
import math

ATR_SIGNATURE = 0x0296
SECTOR_SIZE = 128

def make_atr(output_path, boot_bin, xex_path, lvl_files):
    # Read boot loader (must be exactly 384 bytes = 3 sectors)
    with open(boot_bin, 'rb') as f:
        boot_data = f.read()
    if len(boot_data) > 3 * SECTOR_SIZE:
        print(f"ERROR: Boot loader too large ({len(boot_data)} bytes, max {3*SECTOR_SIZE})")
        sys.exit(1)
    boot_data = boot_data.ljust(3 * SECTOR_SIZE, b'\x00')

    # Read XEX
    with open(xex_path, 'rb') as f:
        xex_data = f.read()
    xex_sectors = math.ceil(len(xex_data) / SECTOR_SIZE)
    print(f"  XEX: {len(xex_data)} bytes, {xex_sectors} sectors (4-{3 + xex_sectors})")

    # Read level files
    lvl_start_sector = 4 + xex_sectors
    all_lvl_data = bytearray()
    for lvl_path in lvl_files:
        with open(lvl_path, 'rb') as f:
            data = f.read()
        lvl_sec_count = math.ceil(len(data) / SECTOR_SIZE)
        sec_begin = lvl_start_sector + len(all_lvl_data) // SECTOR_SIZE
        print(f"  {os.path.basename(lvl_path)}: {len(data)} bytes, sectors {sec_begin}-{sec_begin + lvl_sec_count - 1}")
        # Pad to sector boundary
        padded = data.ljust(lvl_sec_count * SECTOR_SIZE, b'\x00')
        all_lvl_data.extend(padded)

    # Total sectors needed
    total_data = len(boot_data) + xex_data.ljust(xex_sectors * SECTOR_SIZE, b'\x00').__len__() + len(all_lvl_data)
    total_sectors = 3 + xex_sectors + len(all_lvl_data) // SECTOR_SIZE
    total_sectors = max(total_sectors, 720)  # minimum SD size

    # Build disk image
    disk = bytearray(total_sectors * SECTOR_SIZE)

    # Write boot sectors (1-3)
    disk[0:len(boot_data)] = boot_data

    # Write XEX (sector 4+)
    xex_offset = 3 * SECTOR_SIZE
    disk[xex_offset:xex_offset + len(xex_data)] = xex_data

    # Write level data
    lvl_offset = (3 + xex_sectors) * SECTOR_SIZE
    disk[lvl_offset:lvl_offset + len(all_lvl_data)] = all_lvl_data

    # Write ATR file
    image_size = total_sectors * SECTOR_SIZE
    para_size = image_size // 16

    with open(output_path, 'wb') as f:
        header = bytearray(16)
        struct.pack_into('<H', header, 0, ATR_SIGNATURE)
        struct.pack_into('<H', header, 2, para_size & 0xFFFF)
        struct.pack_into('<H', header, 4, SECTOR_SIZE)
        header[6] = (para_size >> 16) & 0xFF
        f.write(header)
        f.write(disk)

    total_size = 16 + image_size
    print(f"\n  ATR: {output_path} ({total_size} bytes, {total_sectors} sectors)")
    print(f"  Level data starts at sector {lvl_start_sector}")

    return lvl_start_sector

def main():
    if len(sys.argv) < 5:
        print("Usage: python make_atr.py output.atr boot.bin doom2d.xex level.lvl [...]")
        sys.exit(1)

    output = sys.argv[1]
    boot_bin = sys.argv[2]
    xex_path = sys.argv[3]
    lvl_files = sys.argv[4:]

    for f in [boot_bin, xex_path] + lvl_files:
        if not os.path.exists(f):
            print(f"ERROR: File not found: {f}")
            sys.exit(1)

    lvl_sector = make_atr(output, boot_bin, xex_path, lvl_files)

    # Write sector layout for ASM include
    layout_path = os.path.join(os.path.dirname(output), '..', 'data', 'atr_layout.asm')
    with open(layout_path, 'w') as f:
        f.write(f"; Auto-generated by make_atr.py - DO NOT EDIT\n")
        f.write(f"LVL_SEC1 = {lvl_sector}\n")
    print(f"  Layout: {layout_path} (LVL_SEC1={lvl_sector})")

if __name__ == '__main__':
    main()
