;==============================================
; DOOM2D - Data tables and binary includes
; data.asm
;==============================================

; ============================================
; SPRITE TABLES (auto-generated in sprite_defs.asm)
; ============================================
        icl 'sprite_defs.asm'

; ============================================
; MAP DATA - stored in VRAM bank $1E, accessed via MEMAC-A at $9000
; ============================================
map_data = MEMW              ; $9000 (MEMAC window = VRAM $01E000+)

; ============================================
; ENTITY SPAWN DATA (generated by map2bin.py)
; ============================================
        icl '../data/test_map_ent.asm'

; ============================================
; BINARY DATA
; ============================================
; palette_data moved to INI segment in main.asm (saves 768B RAM)
; tilesheet_data moved to INI segment in main.asm (saves 4KB RAM)
; hud_font_data moved to INI segment in main.asm (saves 768B RAM)

; ============================================
; Y-ADDRESS LUT (200 entries, Y*320 low/high)
; Used by calc_dst for fast screen address calc
; ============================================
y_addr_lo
:200    dta <[#*320]

y_addr_hi
:200    dta >[#*320]

; Spritesheet is loaded via multi-segment (see main.asm)
; NOT included here - would exceed $C000 RAM limit
