;==============================================
; Auto-generated sprite/tile definitions
; DO NOT EDIT - generated by prepare_sprites.py
;==============================================

; Sprite indices
SPR_PLAYER_IDLE              equ   0  ; 16x32, offset $0000
SPR_PLAYER_WALK1             equ   1  ; 16x32, offset $0200
SPR_PLAYER_WALK2             equ   2  ; 16x32, offset $0400
SPR_PLAYER_WALK3             equ   3  ; 16x32, offset $0600
SPR_PLAYER_SHOOT             equ   4  ; 16x32, offset $0800
SPR_PLAYER_DEATH1            equ   5  ; 16x32, offset $0A00
SPR_ZOMBIE_IDLE              equ   6  ; 16x32, offset $0C00
SPR_ZOMBIE_WALK1             equ   7  ; 16x32, offset $0E00
SPR_ZOMBIE_WALK2             equ   8  ; 16x32, offset $1000
SPR_ZOMBIE_WALK3             equ   9  ; 16x32, offset $1200
SPR_ZOMBIE_SHOOT             equ  10  ; 16x32, offset $1400
SPR_ZOMBIE_DEATH1            equ  11  ; 16x32, offset $1600
SPR_IMP_IDLE                 equ  12  ; 16x32, offset $1800
SPR_IMP_WALK1                equ  13  ; 16x32, offset $1A00
SPR_IMP_WALK2                equ  14  ; 16x32, offset $1C00
SPR_IMP_WALK3                equ  15  ; 16x32, offset $1E00
SPR_IMP_SHOOT                equ  16  ; 16x32, offset $2000
SPR_IMP_DEATH1               equ  17  ; 16x32, offset $2200
SPR_PINKY_IDLE               equ  18  ; 16x32, offset $2400
SPR_PINKY_WALK1              equ  19  ; 16x32, offset $2600
SPR_PINKY_WALK2              equ  20  ; 16x32, offset $2800
SPR_PINKY_WALK3              equ  21  ; 16x32, offset $2A00
SPR_PINKY_ATTACK             equ  22  ; 16x32, offset $2C00
SPR_PINKY_DEATH1             equ  23  ; 16x32, offset $2E00
SPR_CACO_IDLE                equ  24  ; 16x32, offset $3000
SPR_CACO_WALK1               equ  25  ; 16x32, offset $3200
SPR_CACO_WALK2               equ  26  ; 16x32, offset $3400
SPR_CACO_WALK3               equ  27  ; 16x32, offset $3600
SPR_CACO_SHOOT               equ  28  ; 16x32, offset $3800
SPR_CACO_DEATH1              equ  29  ; 16x32, offset $3A00
SPR_SHOTGUN_IDLE             equ  30  ; 16x32, offset $3C00
SPR_SHOTGUN_WALK1            equ  31  ; 16x32, offset $3E00
SPR_SHOTGUN_WALK2            equ  32  ; 16x32, offset $4000
SPR_SHOTGUN_WALK3            equ  33  ; 16x32, offset $4200
SPR_SHOTGUN_SHOOT            equ  34  ; 16x32, offset $4400
SPR_SHOTGUN_DEATH1           equ  35  ; 16x32, offset $4600
SPR_BARON_IDLE               equ  36  ; 16x32, offset $4800
SPR_BARON_WALK1              equ  37  ; 16x32, offset $4A00
SPR_BARON_WALK2              equ  38  ; 16x32, offset $4C00
SPR_BARON_WALK3              equ  39  ; 16x32, offset $4E00
SPR_BARON_SHOOT              equ  40  ; 16x32, offset $5000
SPR_BARON_DEATH1             equ  41  ; 16x32, offset $5200
SPR_PROJECTILE1              equ  42  ; 8x8, offset $5400
SPR_PROJECTILE2              equ  43  ; 8x8, offset $5440
SPR_MEDIKIT                  equ  44  ; 16x16, offset $5500
SPR_STIMPACK                 equ  45  ; 16x16, offset $5600
SPR_HEALTH_BONUS             equ  46  ; 16x16, offset $5700
SPR_AMMO_CLIP                equ  47  ; 16x16, offset $5800
SPR_GREENARMOR               equ  48  ; 16x16, offset $AD00
SPR_BLUEARMOR                equ  49  ; 16x16, offset $AE00
SPR_SOULSPHERE               equ  50  ; 16x16, offset $AF00
SPR_KEYRED                   equ  51  ; 16x16, offset $B000
SPR_KEYBLUE                  equ  52  ; 16x16, offset $B100
SPR_KEYYELLOW                equ  53  ; 16x16, offset $B200
SPR_SHOTGUNPK                equ  54  ; 16x16, offset $B300
SPR_SHELLS                   equ  55  ; 16x16, offset $B400
SPR_BARREL                   equ  56  ; 16x16, offset $B500
SPR_PILLAR                   equ  57  ; 16x32, offset $B600
SPR_TORCH                    equ  58  ; 16x32, offset $B800
SPR_LAMP                     equ  59  ; 16x32, offset $BA00
SPR_PLAYER_IDLE_L            equ  60  ; 16x32, offset $5900
SPR_PLAYER_WALK1_L           equ  61  ; 16x32, offset $5B00
SPR_PLAYER_WALK2_L           equ  62  ; 16x32, offset $5D00
SPR_PLAYER_WALK3_L           equ  63  ; 16x32, offset $5F00
SPR_PLAYER_SHOOT_L           equ  64  ; 16x32, offset $6100
SPR_PLAYER_DEATH1_L          equ  65  ; 16x32, offset $6300
SPR_ZOMBIE_IDLE_L            equ  66  ; 16x32, offset $6500
SPR_ZOMBIE_WALK1_L           equ  67  ; 16x32, offset $6700
SPR_ZOMBIE_WALK2_L           equ  68  ; 16x32, offset $6900
SPR_ZOMBIE_WALK3_L           equ  69  ; 16x32, offset $6B00
SPR_ZOMBIE_SHOOT_L           equ  70  ; 16x32, offset $6D00
SPR_ZOMBIE_DEATH1_L          equ  71  ; 16x32, offset $6F00
SPR_IMP_IDLE_L               equ  72  ; 16x32, offset $7100
SPR_IMP_WALK1_L              equ  73  ; 16x32, offset $7300
SPR_IMP_WALK2_L              equ  74  ; 16x32, offset $7500
SPR_IMP_WALK3_L              equ  75  ; 16x32, offset $7700
SPR_IMP_SHOOT_L              equ  76  ; 16x32, offset $7900
SPR_IMP_DEATH1_L             equ  77  ; 16x32, offset $7B00
SPR_PINKY_IDLE_L             equ  78  ; 16x32, offset $7D00
SPR_PINKY_WALK1_L            equ  79  ; 16x32, offset $7F00
SPR_PINKY_WALK2_L            equ  80  ; 16x32, offset $8100
SPR_PINKY_WALK3_L            equ  81  ; 16x32, offset $8300
SPR_PINKY_ATTACK_L           equ  82  ; 16x32, offset $8500
SPR_PINKY_DEATH1_L           equ  83  ; 16x32, offset $8700
SPR_CACO_IDLE_L              equ  84  ; 16x32, offset $8900
SPR_CACO_WALK1_L             equ  85  ; 16x32, offset $8B00
SPR_CACO_WALK2_L             equ  86  ; 16x32, offset $8D00
SPR_CACO_WALK3_L             equ  87  ; 16x32, offset $8F00
SPR_CACO_SHOOT_L             equ  88  ; 16x32, offset $9100
SPR_CACO_DEATH1_L            equ  89  ; 16x32, offset $9300
SPR_SHOTGUN_IDLE_L           equ  90  ; 16x32, offset $9500
SPR_SHOTGUN_WALK1_L          equ  91  ; 16x32, offset $9700
SPR_SHOTGUN_WALK2_L          equ  92  ; 16x32, offset $9900
SPR_SHOTGUN_WALK3_L          equ  93  ; 16x32, offset $9B00
SPR_SHOTGUN_SHOOT_L          equ  94  ; 16x32, offset $9D00
SPR_SHOTGUN_DEATH1_L         equ  95  ; 16x32, offset $9F00
SPR_BARON_IDLE_L             equ  96  ; 16x32, offset $A100
SPR_BARON_WALK1_L            equ  97  ; 16x32, offset $A300
SPR_BARON_WALK2_L            equ  98  ; 16x32, offset $A500
SPR_BARON_WALK3_L            equ  99  ; 16x32, offset $A700
SPR_BARON_SHOOT_L            equ 100  ; 16x32, offset $A900
SPR_BARON_DEATH1_L           equ 101  ; 16x32, offset $AB00
SPR_CHAINGUNPK               equ 102  ; 16x16, offset $BC00
SPR_ROCKETPK                 equ 103  ; 16x16, offset $BD00
SPR_ROCKET_PROJ              equ 104  ; 8x8, offset $BE00
SPR_ROCKETBOX                equ 105  ; 16x16, offset $BF00
; --- New sprites in VRAM $031000+ (chunk5, bank $31) ---
SPR_ZOMBIE_DEATH2            equ 106  ; 16x32, VRAM $031000
SPR_ZOMBIE_DEATH3            equ 107  ; 16x32, VRAM $031200
SPR_ZOMBIE_GIB1              equ 108  ; 16x32, VRAM $031400
SPR_ZOMBIE_GIB2              equ 109  ; 16x32, VRAM $031600
SPR_IMP_GIB1                 equ 110  ; 16x32, VRAM $031800
SPR_IMP_GIB2                 equ 111  ; 16x32, VRAM $031A00
SPR_SHOTGUN_GIB1             equ 112  ; 16x32, VRAM $031C00
SPR_SHOTGUN_GIB2             equ 113  ; 16x32, VRAM $031E00
; --- Death2/3 for all types (chunk5 offset $1900+, VRAM $032900+) ---
SPR_IMP_DEATH2               equ 114  ; 16x32
SPR_IMP_DEATH3               equ 115  ; 16x32
SPR_SHOTGUN_DEATH2           equ 116  ; 16x32
SPR_SHOTGUN_DEATH3           equ 117  ; 16x32
SPR_PINKY_DEATH2             equ 118  ; 16x32
SPR_PINKY_DEATH3             equ 119  ; 16x32
SPR_CACO_DEATH2              equ 120  ; 16x32
SPR_CACO_DEATH3              equ 121  ; 16x32
SPR_BARON_DEATH2             equ 122  ; 16x32
SPR_BARON_DEATH3             equ 123  ; 16x32
SPR_BARREL_EXP1              equ 124  ; 16x32 (flash)
SPR_BARREL_EXP2              equ 125  ; 16x32 (fire)
SPR_BARREL_EXP3              equ 126  ; 16x32 (smoke)
SPR_PLASMAGUNPK              equ 127  ; 16x16, VRAM $01F000
SPR_CELLSPK                  equ 128  ; 16x16, VRAM $01F100
SPR_PLASMA_PROJ1             equ 129  ; 8x8,   VRAM $01F200
SPR_PLASMA_PROJ2             equ 130  ; 8x8,   VRAM $01F240
SPR_BFG_PROJ1                equ 131  ; 16x16, VRAM $01F280
SPR_BFG_PROJ2                equ 132  ; 16x16, VRAM $01F380
SPR_BFGPK                   equ 133  ; 16x16, VRAM $01F480
SPR_ROCKET1PK                equ 134  ; 16x16, VRAM $01F580
SPR_ARMORBONUS               equ 135  ; 16x16, VRAM $01F680
SPR_PL_DEATH2                equ 136  ; 16x32, VRAM $01F780
SPR_PL_DEATH3                equ 137  ; 16x32, VRAM $01F980
SPR_IMP_FIRE1                equ 138  ; 8x8,   VRAM $01E400
SPR_IMP_FIRE2                equ 139  ; 8x8,   VRAM $01E440
SPR_PL_PAIN                  equ 140  ; 16x32, VRAM $051000
SPR_PL_PAIN_L                equ 141  ; 16x32, VRAM $051200
SPR_ZOMBIE_PAIN              equ 142  ; 16x32, VRAM $051400
SPR_ZOMBIE_PAIN_L            equ 143  ; 16x32, VRAM $051600
SPR_CACO_FIRE1               equ 144  ; 8x8,   VRAM $01E480
SPR_CACO_FIRE2               equ 145  ; 8x8,   VRAM $01E4C0
SPRITESHEET_SIZE         equ $C000      ; chunks 1-4 (49152 bytes)

; Player sprite aliases
SPR_PL_IDLE              equ 0
SPR_PL_W1                equ 1
SPR_PL_W2                equ 2
SPR_PL_W3                equ 3
SPR_PL_SHOOT             equ 4
SPR_PL_DEATH             equ 5

SPR_PROJ1                         equ  42
SPR_PROJ2                         equ  43


MIRROR_OFFSET            equ  60

; Enemy types
EN_ZOMBIE                       equ 0
EN_IMP                          equ 1
EN_PINKY                        equ 2
EN_CACO                         equ 3
EN_SHOTGUN                      equ 4
EN_BARON                        equ 5

; Sprite VRAM offset tables
spr_off_lo
        dta <$0000  ; player_idle
        dta <$0200  ; player_walk1
        dta <$0400  ; player_walk2
        dta <$0600  ; player_walk3
        dta <$0800  ; player_shoot
        dta <$0A00  ; player_death1
        dta <$0C00  ; zombie_idle
        dta <$0E00  ; zombie_walk1
        dta <$1000  ; zombie_walk2
        dta <$1200  ; zombie_walk3
        dta <$1400  ; zombie_shoot
        dta <$1600  ; zombie_death1
        dta <$1800  ; imp_idle
        dta <$1A00  ; imp_walk1
        dta <$1C00  ; imp_walk2
        dta <$1E00  ; imp_walk3
        dta <$2000  ; imp_shoot
        dta <$2200  ; imp_death1
        dta <$2400  ; pinky_idle
        dta <$2600  ; pinky_walk1
        dta <$2800  ; pinky_walk2
        dta <$2A00  ; pinky_walk3
        dta <$2C00  ; pinky_attack
        dta <$2E00  ; pinky_death1
        dta <$3000  ; caco_idle
        dta <$3200  ; caco_walk1
        dta <$3400  ; caco_walk2
        dta <$3600  ; caco_walk3
        dta <$3800  ; caco_shoot
        dta <$3A00  ; caco_death1
        dta <$3C00  ; shotgun_idle
        dta <$3E00  ; shotgun_walk1
        dta <$4000  ; shotgun_walk2
        dta <$4200  ; shotgun_walk3
        dta <$4400  ; shotgun_shoot
        dta <$4600  ; shotgun_death1
        dta <$4800  ; baron_idle
        dta <$4A00  ; baron_walk1
        dta <$4C00  ; baron_walk2
        dta <$4E00  ; baron_walk3
        dta <$5000  ; baron_shoot
        dta <$5200  ; baron_death1
        dta <$5400  ; projectile1
        dta <$5440  ; projectile2
        dta <$5500  ; medikit
        dta <$5600  ; stimpack
        dta <$5700  ; health_bonus
        dta <$5800  ; ammo_clip
        dta <$AD00  ; greenarmor
        dta <$AE00  ; bluearmor
        dta <$AF00  ; soulsphere
        dta <$B000  ; keyred
        dta <$B100  ; keyblue
        dta <$B200  ; keyyellow
        dta <$B300  ; shotgunpk
        dta <$B400  ; shells
        dta <$B500  ; barrel
        dta <$B600  ; pillar
        dta <$B800  ; torch
        dta <$BA00  ; lamp
        dta <$5900  ; player_idle_L
        dta <$5B00  ; player_walk1_L
        dta <$5D00  ; player_walk2_L
        dta <$5F00  ; player_walk3_L
        dta <$6100  ; player_shoot_L
        dta <$6300  ; player_death1_L
        dta <$6500  ; zombie_idle_L
        dta <$6700  ; zombie_walk1_L
        dta <$6900  ; zombie_walk2_L
        dta <$6B00  ; zombie_walk3_L
        dta <$6D00  ; zombie_shoot_L
        dta <$6F00  ; zombie_death1_L
        dta <$7100  ; imp_idle_L
        dta <$7300  ; imp_walk1_L
        dta <$7500  ; imp_walk2_L
        dta <$7700  ; imp_walk3_L
        dta <$7900  ; imp_shoot_L
        dta <$7B00  ; imp_death1_L
        dta <$7D00  ; pinky_idle_L
        dta <$7F00  ; pinky_walk1_L
        dta <$8100  ; pinky_walk2_L
        dta <$8300  ; pinky_walk3_L
        dta <$8500  ; pinky_attack_L
        dta <$8700  ; pinky_death1_L
        dta <$8900  ; caco_idle_L
        dta <$8B00  ; caco_walk1_L
        dta <$8D00  ; caco_walk2_L
        dta <$8F00  ; caco_walk3_L
        dta <$9100  ; caco_shoot_L
        dta <$9300  ; caco_death1_L
        dta <$9500  ; shotgun_idle_L
        dta <$9700  ; shotgun_walk1_L
        dta <$9900  ; shotgun_walk2_L
        dta <$9B00  ; shotgun_walk3_L
        dta <$9D00  ; shotgun_shoot_L
        dta <$9F00  ; shotgun_death1_L
        dta <$A100  ; baron_idle_L
        dta <$A300  ; baron_walk1_L
        dta <$A500  ; baron_walk2_L
        dta <$A700  ; baron_walk3_L
        dta <$A900  ; baron_shoot_L
        dta <$AB00  ; baron_death1_L
        dta <$BC00  ; chaingunpk
        dta <$BD00  ; rocketpk
        dta <$BE00  ; rocket_proj
        dta <$BF00  ; rocketbox
        dta <$0000  ; zombie_death2 (VRAM $031000)
        dta <$0000  ; zombie_death3 (VRAM $031200)
        dta <$0000  ; zombie_gib1 (VRAM $031400)
        dta <$0000  ; zombie_gib2 (VRAM $031600)
        dta <$0000  ; imp_gib1 (VRAM $031800)
        dta <$0000  ; imp_gib2 (VRAM $031A00)
        dta <$0000  ; shotgun_gib1 (VRAM $031C00)
        dta <$0000  ; shotgun_gib2 (VRAM $031E00)
        dta <$0000  ; imp_death2
        dta <$0000  ; imp_death3
        dta <$0000  ; shotgun_death2
        dta <$0000  ; shotgun_death3
        dta <$0000  ; pinky_death2
        dta <$0000  ; pinky_death3
        dta <$0000  ; caco_death2
        dta <$0000  ; caco_death3
        dta <$0000  ; baron_death2
        dta <$0000  ; baron_death3
        dta <$0000  ; barrel_exp1
        dta <$0000  ; barrel_exp2
        dta <$0000  ; barrel_exp3
        dta <$0000  ; plasmagunpk (VRAM $01F000)
        dta <$0000  ; cellspk (VRAM $01F100)
        dta <$0000  ; plasma_proj1 (VRAM $01F200)
        dta <$0040  ; plasma_proj2 (VRAM $01F240)
        dta <$0080  ; bfg_proj1 (VRAM $01F280)
        dta <$0080  ; bfg_proj2 (VRAM $01F380)
        dta <$0080  ; bfgpk (VRAM $01F480)
        dta <$0080  ; rocket1pk (VRAM $01F580)
        dta <$0080  ; armorbonus (VRAM $01F680)
        dta <$0080  ; pl_death2 (VRAM $01F780)
        dta <$0080  ; pl_death3 (VRAM $01F980)
        dta <$0000  ; imp_fire1 (VRAM $01E400)
        dta <$0040  ; imp_fire2 (VRAM $01E440)
        dta <$0000  ; pl_pain (VRAM $051000)
        dta <$0000  ; pl_pain_L (VRAM $051200)
        dta <$0000  ; zombie_pain (VRAM $051400)
        dta <$0000  ; zombie_pain_L (VRAM $051600)
        dta <$0080  ; caco_fire1 (VRAM $01E480)
        dta <$00C0  ; caco_fire2 (VRAM $01E4C0)

spr_off_hi
        dta >$0000  ; player_idle
        dta >$0200  ; player_walk1
        dta >$0400  ; player_walk2
        dta >$0600  ; player_walk3
        dta >$0800  ; player_shoot
        dta >$0A00  ; player_death1
        dta >$0C00  ; zombie_idle
        dta >$0E00  ; zombie_walk1
        dta >$1000  ; zombie_walk2
        dta >$1200  ; zombie_walk3
        dta >$1400  ; zombie_shoot
        dta >$1600  ; zombie_death1
        dta >$1800  ; imp_idle
        dta >$1A00  ; imp_walk1
        dta >$1C00  ; imp_walk2
        dta >$1E00  ; imp_walk3
        dta >$2000  ; imp_shoot
        dta >$2200  ; imp_death1
        dta >$2400  ; pinky_idle
        dta >$2600  ; pinky_walk1
        dta >$2800  ; pinky_walk2
        dta >$2A00  ; pinky_walk3
        dta >$2C00  ; pinky_attack
        dta >$2E00  ; pinky_death1
        dta >$3000  ; caco_idle
        dta >$3200  ; caco_walk1
        dta >$3400  ; caco_walk2
        dta >$3600  ; caco_walk3
        dta >$3800  ; caco_shoot
        dta >$3A00  ; caco_death1
        dta >$3C00  ; shotgun_idle
        dta >$3E00  ; shotgun_walk1
        dta >$4000  ; shotgun_walk2
        dta >$4200  ; shotgun_walk3
        dta >$4400  ; shotgun_shoot
        dta >$4600  ; shotgun_death1
        dta >$4800  ; baron_idle
        dta >$4A00  ; baron_walk1
        dta >$4C00  ; baron_walk2
        dta >$4E00  ; baron_walk3
        dta >$5000  ; baron_shoot
        dta >$5200  ; baron_death1
        dta >$5400  ; projectile1
        dta >$5440  ; projectile2
        dta >$5500  ; medikit
        dta >$5600  ; stimpack
        dta >$5700  ; health_bonus
        dta >$5800  ; ammo_clip
        dta >$AD00  ; greenarmor
        dta >$AE00  ; bluearmor
        dta >$AF00  ; soulsphere
        dta >$B000  ; keyred
        dta >$B100  ; keyblue
        dta >$B200  ; keyyellow
        dta >$B300  ; shotgunpk
        dta >$B400  ; shells
        dta >$B500  ; barrel
        dta >$B600  ; pillar
        dta >$B800  ; torch
        dta >$BA00  ; lamp
        dta >$5900  ; player_idle_L
        dta >$5B00  ; player_walk1_L
        dta >$5D00  ; player_walk2_L
        dta >$5F00  ; player_walk3_L
        dta >$6100  ; player_shoot_L
        dta >$6300  ; player_death1_L
        dta >$6500  ; zombie_idle_L
        dta >$6700  ; zombie_walk1_L
        dta >$6900  ; zombie_walk2_L
        dta >$6B00  ; zombie_walk3_L
        dta >$6D00  ; zombie_shoot_L
        dta >$6F00  ; zombie_death1_L
        dta >$7100  ; imp_idle_L
        dta >$7300  ; imp_walk1_L
        dta >$7500  ; imp_walk2_L
        dta >$7700  ; imp_walk3_L
        dta >$7900  ; imp_shoot_L
        dta >$7B00  ; imp_death1_L
        dta >$7D00  ; pinky_idle_L
        dta >$7F00  ; pinky_walk1_L
        dta >$8100  ; pinky_walk2_L
        dta >$8300  ; pinky_walk3_L
        dta >$8500  ; pinky_attack_L
        dta >$8700  ; pinky_death1_L
        dta >$8900  ; caco_idle_L
        dta >$8B00  ; caco_walk1_L
        dta >$8D00  ; caco_walk2_L
        dta >$8F00  ; caco_walk3_L
        dta >$9100  ; caco_shoot_L
        dta >$9300  ; caco_death1_L
        dta >$9500  ; shotgun_idle_L
        dta >$9700  ; shotgun_walk1_L
        dta >$9900  ; shotgun_walk2_L
        dta >$9B00  ; shotgun_walk3_L
        dta >$9D00  ; shotgun_shoot_L
        dta >$9F00  ; shotgun_death1_L
        dta >$A100  ; baron_idle_L
        dta >$A300  ; baron_walk1_L
        dta >$A500  ; baron_walk2_L
        dta >$A700  ; baron_walk3_L
        dta >$A900  ; baron_shoot_L
        dta >$AB00  ; baron_death1_L
        dta >$BC00  ; chaingunpk
        dta >$BD00  ; rocketpk
        dta >$BE00  ; rocket_proj
        dta >$BF00  ; rocketbox
        dta >$0000  ; zombie_death2 (VRAM $031000)
        dta >$0200  ; zombie_death3 (VRAM $031200)
        dta >$0400  ; zombie_gib1 (VRAM $031400)
        dta >$0600  ; zombie_gib2 (VRAM $031600)
        dta >$0800  ; imp_gib1 (VRAM $031800)
        dta >$0A00  ; imp_gib2 (VRAM $031A00)
        dta >$0C00  ; shotgun_gib1 (VRAM $031C00)
        dta >$0E00  ; shotgun_gib2 (VRAM $031E00)
        dta >$EC00  ; imp_death2 (VRAM $01FC00, in c6)
        dta >$EE00  ; imp_death3 (VRAM $01FE00, in c6)
        dta >$1D00  ; shotgun_death2
        dta >$1F00  ; shotgun_death3
        dta >$2100  ; pinky_death2
        dta >$2300  ; pinky_death3
        dta >$2500  ; caco_death2
        dta >$2700  ; caco_death3
        dta >$2900  ; baron_death2
        dta >$2B00  ; baron_death3
        dta >$2D00  ; barrel_exp1 (16x16, 256B each)
        dta >$2E00  ; barrel_exp2
        dta >$2F00  ; barrel_exp3
        dta >$E000  ; plasmagunpk ($01F000: hi=$E0, +$10=$F0)
        dta >$E100  ; cellspk ($01F100: hi=$E1, +$10=$F1)
        dta >$E200  ; plasma_proj1 ($01F200)
        dta >$E200  ; plasma_proj2 ($01F240, same hi byte)
        dta >$E200  ; bfg_proj1 ($01F280)
        dta >$E300  ; bfg_proj2 ($01F380)
        dta >$E400  ; bfgpk ($01F480)
        dta >$E500  ; rocket1pk ($01F580)
        dta >$E600  ; armorbonus ($01F680)
        dta >$E700  ; pl_death2 ($01F780)
        dta >$E900  ; pl_death3 ($01F980)
        dta >$D400  ; imp_fire1 ($01E400, +$10=$E4)
        dta >$D440  ; imp_fire2 ($01E440, +$10=$E4)
        dta >$0000  ; pl_pain ($051000, +$10=$10)
        dta >$0200  ; pl_pain_L ($051200, +$10=$12)
        dta >$0400  ; zombie_pain ($051400, +$10=$14)
        dta >$0600  ; zombie_pain_L ($051600, +$10=$16)
        dta >$D480  ; caco_fire1 ($01E480, +$10=$E4)
        dta >$D4C0  ; caco_fire2 ($01E4C0, +$10=$E4)

; Sprite VRAM bank table (high byte of 24-bit VRAM address)
; $01 = banks $10-$1F (VRAM $01xxxx), $03 = banks $30+ (VRAM $03xxxx)
spr_off_bank
        dta $01  ; player_idle
        dta $01  ; player_walk1
        dta $01  ; player_walk2
        dta $01  ; player_walk3
        dta $01  ; player_shoot
        dta $01  ; player_death1
        dta $01  ; zombie_idle
        dta $01  ; zombie_walk1
        dta $01  ; zombie_walk2
        dta $01  ; zombie_walk3
        dta $01  ; zombie_shoot
        dta $01  ; zombie_death1
        dta $01  ; imp_idle
        dta $01  ; imp_walk1
        dta $01  ; imp_walk2
        dta $01  ; imp_walk3
        dta $01  ; imp_shoot
        dta $01  ; imp_death1
        dta $01  ; pinky_idle
        dta $01  ; pinky_walk1
        dta $01  ; pinky_walk2
        dta $01  ; pinky_walk3
        dta $01  ; pinky_attack
        dta $01  ; pinky_death1
        dta $01  ; caco_idle
        dta $01  ; caco_walk1
        dta $01  ; caco_walk2
        dta $01  ; caco_walk3
        dta $01  ; caco_shoot
        dta $01  ; caco_death1
        dta $01  ; shotgun_idle
        dta $01  ; shotgun_walk1
        dta $01  ; shotgun_walk2
        dta $01  ; shotgun_walk3
        dta $01  ; shotgun_shoot
        dta $01  ; shotgun_death1
        dta $01  ; baron_idle
        dta $01  ; baron_walk1
        dta $01  ; baron_walk2
        dta $01  ; baron_walk3
        dta $01  ; baron_shoot
        dta $01  ; baron_death1
        dta $01  ; projectile1
        dta $01  ; projectile2
        dta $01  ; medikit
        dta $01  ; stimpack
        dta $01  ; health_bonus
        dta $01  ; ammo_clip
        dta $01  ; greenarmor
        dta $01  ; bluearmor
        dta $01  ; soulsphere
        dta $01  ; keyred
        dta $01  ; keyblue
        dta $01  ; keyyellow
        dta $01  ; shotgunpk
        dta $01  ; shells
        dta $01  ; barrel
        dta $01  ; pillar
        dta $01  ; torch
        dta $01  ; lamp
        dta $01  ; player_idle_L
        dta $01  ; player_walk1_L
        dta $01  ; player_walk2_L
        dta $01  ; player_walk3_L
        dta $01  ; player_shoot_L
        dta $01  ; player_death1_L
        dta $01  ; zombie_idle_L
        dta $01  ; zombie_walk1_L
        dta $01  ; zombie_walk2_L
        dta $01  ; zombie_walk3_L
        dta $01  ; zombie_shoot_L
        dta $01  ; zombie_death1_L
        dta $01  ; imp_idle_L
        dta $01  ; imp_walk1_L
        dta $01  ; imp_walk2_L
        dta $01  ; imp_walk3_L
        dta $01  ; imp_shoot_L
        dta $01  ; imp_death1_L
        dta $01  ; pinky_idle_L
        dta $01  ; pinky_walk1_L
        dta $01  ; pinky_walk2_L
        dta $01  ; pinky_walk3_L
        dta $01  ; pinky_attack_L
        dta $01  ; pinky_death1_L
        dta $01  ; caco_idle_L
        dta $01  ; caco_walk1_L
        dta $01  ; caco_walk2_L
        dta $01  ; caco_walk3_L
        dta $01  ; caco_shoot_L
        dta $01  ; caco_death1_L
        dta $01  ; shotgun_idle_L
        dta $01  ; shotgun_walk1_L
        dta $01  ; shotgun_walk2_L
        dta $01  ; shotgun_walk3_L
        dta $01  ; shotgun_shoot_L
        dta $01  ; shotgun_death1_L
        dta $01  ; baron_idle_L
        dta $01  ; baron_walk1_L
        dta $01  ; baron_walk2_L
        dta $01  ; baron_walk3_L
        dta $01  ; baron_shoot_L
        dta $01  ; baron_death1_L
        dta $01  ; chaingunpk
        dta $01  ; rocketpk
        dta $01  ; rocket_proj
        dta $01  ; rocketbox
        dta $03  ; zombie_death2 (VRAM $03xxxx)
        dta $03  ; zombie_death3 (VRAM $03xxxx)
        dta $03  ; zombie_gib1
        dta $03  ; zombie_gib2
        dta $03  ; imp_gib1
        dta $03  ; imp_gib2
        dta $03  ; shotgun_gib1
        dta $03  ; shotgun_gib2
        dta $01  ; imp_death2 (moved to c6, VRAM $01FC00)
        dta $01  ; imp_death3 (moved to c6, VRAM $01FE00)
        dta $03  ; shotgun_death2
        dta $03  ; shotgun_death3
        dta $03  ; pinky_death2
        dta $03  ; pinky_death3
        dta $03  ; caco_death2
        dta $03  ; caco_death3
        dta $03  ; baron_death2
        dta $03  ; baron_death3
        dta $03  ; barrel_exp1
        dta $03  ; barrel_exp2
        dta $03  ; barrel_exp3
        dta $01  ; plasmagunpk (VRAM $01xxxx)
        dta $01  ; cellspk (VRAM $01xxxx)
        dta $01  ; plasma_proj1
        dta $01  ; plasma_proj2
        dta $01  ; bfg_proj1
        dta $01  ; bfg_proj2
        dta $01  ; bfgpk
        dta $01  ; rocket1pk
        dta $01  ; armorbonus
        dta $01  ; pl_death2
        dta $01  ; pl_death3
        dta $01  ; imp_fire1
        dta $01  ; imp_fire2
        dta $05  ; pl_pain (VRAM $05xxxx)
        dta $05  ; pl_pain_L (VRAM $05xxxx)
        dta $05  ; zombie_pain
        dta $05  ; zombie_pain_L
        dta $01  ; caco_fire1 (VRAM $01xxxx)
        dta $01  ; caco_fire2 (VRAM $01xxxx)

; Sprite width/height tables
spr_w
        dta 16  ; player_idle
        dta 16  ; player_walk1
        dta 16  ; player_walk2
        dta 16  ; player_walk3
        dta 16  ; player_shoot
        dta 16  ; player_death1
        dta 16  ; zombie_idle
        dta 16  ; zombie_walk1
        dta 16  ; zombie_walk2
        dta 16  ; zombie_walk3
        dta 16  ; zombie_shoot
        dta 16  ; zombie_death1
        dta 16  ; imp_idle
        dta 16  ; imp_walk1
        dta 16  ; imp_walk2
        dta 16  ; imp_walk3
        dta 16  ; imp_shoot
        dta 16  ; imp_death1
        dta 16  ; pinky_idle
        dta 16  ; pinky_walk1
        dta 16  ; pinky_walk2
        dta 16  ; pinky_walk3
        dta 16  ; pinky_attack
        dta 16  ; pinky_death1
        dta 16  ; caco_idle
        dta 16  ; caco_walk1
        dta 16  ; caco_walk2
        dta 16  ; caco_walk3
        dta 16  ; caco_shoot
        dta 16  ; caco_death1
        dta 16  ; shotgun_idle
        dta 16  ; shotgun_walk1
        dta 16  ; shotgun_walk2
        dta 16  ; shotgun_walk3
        dta 16  ; shotgun_shoot
        dta 16  ; shotgun_death1
        dta 16  ; baron_idle
        dta 16  ; baron_walk1
        dta 16  ; baron_walk2
        dta 16  ; baron_walk3
        dta 16  ; baron_shoot
        dta 16  ; baron_death1
        dta 8  ; projectile1
        dta 8  ; projectile2
        dta 16  ; medikit
        dta 16  ; stimpack
        dta 16  ; health_bonus
        dta 16  ; ammo_clip
        dta 16  ; greenarmor
        dta 16  ; bluearmor
        dta 16  ; soulsphere
        dta 16  ; keyred
        dta 16  ; keyblue
        dta 16  ; keyyellow
        dta 16  ; shotgunpk
        dta 16  ; shells
        dta 16  ; barrel
        dta 16  ; pillar
        dta 16  ; torch
        dta 16  ; lamp
        dta 16  ; player_idle_L
        dta 16  ; player_walk1_L
        dta 16  ; player_walk2_L
        dta 16  ; player_walk3_L
        dta 16  ; player_shoot_L
        dta 16  ; player_death1_L
        dta 16  ; zombie_idle_L
        dta 16  ; zombie_walk1_L
        dta 16  ; zombie_walk2_L
        dta 16  ; zombie_walk3_L
        dta 16  ; zombie_shoot_L
        dta 16  ; zombie_death1_L
        dta 16  ; imp_idle_L
        dta 16  ; imp_walk1_L
        dta 16  ; imp_walk2_L
        dta 16  ; imp_walk3_L
        dta 16  ; imp_shoot_L
        dta 16  ; imp_death1_L
        dta 16  ; pinky_idle_L
        dta 16  ; pinky_walk1_L
        dta 16  ; pinky_walk2_L
        dta 16  ; pinky_walk3_L
        dta 16  ; pinky_attack_L
        dta 16  ; pinky_death1_L
        dta 16  ; caco_idle_L
        dta 16  ; caco_walk1_L
        dta 16  ; caco_walk2_L
        dta 16  ; caco_walk3_L
        dta 16  ; caco_shoot_L
        dta 16  ; caco_death1_L
        dta 16  ; shotgun_idle_L
        dta 16  ; shotgun_walk1_L
        dta 16  ; shotgun_walk2_L
        dta 16  ; shotgun_walk3_L
        dta 16  ; shotgun_shoot_L
        dta 16  ; shotgun_death1_L
        dta 16  ; baron_idle_L
        dta 16  ; baron_walk1_L
        dta 16  ; baron_walk2_L
        dta 16  ; baron_walk3_L
        dta 16  ; baron_shoot_L
        dta 16  ; baron_death1_L
        dta 16  ; chaingunpk
        dta 16  ; rocketpk
        dta 8   ; rocket_proj
        dta 16  ; rocketbox
        dta 16  ; zombie_death2
        dta 16  ; zombie_death3
        dta 16  ; zombie_gib1
        dta 16  ; zombie_gib2
        dta 16  ; imp_gib1
        dta 16  ; imp_gib2
        dta 16  ; shotgun_gib1
        dta 16  ; shotgun_gib2
        dta 16  ; imp_death2
        dta 16  ; imp_death3
        dta 16  ; shotgun_death2
        dta 16  ; shotgun_death3
        dta 16  ; pinky_death2
        dta 16  ; pinky_death3
        dta 16  ; caco_death2
        dta 16  ; caco_death3
        dta 16  ; baron_death2
        dta 16  ; baron_death3
        dta 16  ; barrel_exp1 (16x16)
        dta 16  ; barrel_exp2 (16x16)
        dta 16  ; barrel_exp3 (16x16)
        dta 16  ; plasmagunpk
        dta 16  ; cellspk
        dta 8   ; plasma_proj1
        dta 8   ; plasma_proj2
        dta 16  ; bfg_proj1
        dta 16  ; bfg_proj2
        dta 16  ; bfgpk
        dta 16  ; rocket1pk
        dta 16  ; armorbonus
        dta 16  ; pl_death2
        dta 16  ; pl_death3
        dta 8   ; imp_fire1
        dta 8   ; imp_fire2
        dta 16  ; pl_pain
        dta 16  ; pl_pain_L
        dta 16  ; zombie_pain
        dta 16  ; zombie_pain_L
        dta 8   ; caco_fire1
        dta 8   ; caco_fire2

spr_h
        dta 32  ; player_idle
        dta 32  ; player_walk1
        dta 32  ; player_walk2
        dta 32  ; player_walk3
        dta 32  ; player_shoot
        dta 32  ; player_death1
        dta 32  ; zombie_idle
        dta 32  ; zombie_walk1
        dta 32  ; zombie_walk2
        dta 32  ; zombie_walk3
        dta 32  ; zombie_shoot
        dta 32  ; zombie_death1
        dta 32  ; imp_idle
        dta 32  ; imp_walk1
        dta 32  ; imp_walk2
        dta 32  ; imp_walk3
        dta 32  ; imp_shoot
        dta 32  ; imp_death1
        dta 32  ; pinky_idle
        dta 32  ; pinky_walk1
        dta 32  ; pinky_walk2
        dta 32  ; pinky_walk3
        dta 32  ; pinky_attack
        dta 32  ; pinky_death1
        dta 32  ; caco_idle
        dta 32  ; caco_walk1
        dta 32  ; caco_walk2
        dta 32  ; caco_walk3
        dta 32  ; caco_shoot
        dta 32  ; caco_death1
        dta 32  ; shotgun_idle
        dta 32  ; shotgun_walk1
        dta 32  ; shotgun_walk2
        dta 32  ; shotgun_walk3
        dta 32  ; shotgun_shoot
        dta 32  ; shotgun_death1
        dta 32  ; baron_idle
        dta 32  ; baron_walk1
        dta 32  ; baron_walk2
        dta 32  ; baron_walk3
        dta 32  ; baron_shoot
        dta 32  ; baron_death1
        dta 8  ; projectile1
        dta 8  ; projectile2
        dta 16  ; medikit
        dta 16  ; stimpack
        dta 16  ; health_bonus
        dta 16  ; ammo_clip
        dta 16  ; greenarmor
        dta 16  ; bluearmor
        dta 16  ; soulsphere
        dta 16  ; keyred
        dta 16  ; keyblue
        dta 16  ; keyyellow
        dta 16  ; shotgunpk
        dta 16  ; shells
        dta 16  ; barrel
        dta 32  ; pillar
        dta 32  ; torch
        dta 32  ; lamp
        dta 32  ; player_idle_L
        dta 32  ; player_walk1_L
        dta 32  ; player_walk2_L
        dta 32  ; player_walk3_L
        dta 32  ; player_shoot_L
        dta 32  ; player_death1_L
        dta 32  ; zombie_idle_L
        dta 32  ; zombie_walk1_L
        dta 32  ; zombie_walk2_L
        dta 32  ; zombie_walk3_L
        dta 32  ; zombie_shoot_L
        dta 32  ; zombie_death1_L
        dta 32  ; imp_idle_L
        dta 32  ; imp_walk1_L
        dta 32  ; imp_walk2_L
        dta 32  ; imp_walk3_L
        dta 32  ; imp_shoot_L
        dta 32  ; imp_death1_L
        dta 32  ; pinky_idle_L
        dta 32  ; pinky_walk1_L
        dta 32  ; pinky_walk2_L
        dta 32  ; pinky_walk3_L
        dta 32  ; pinky_attack_L
        dta 32  ; pinky_death1_L
        dta 32  ; caco_idle_L
        dta 32  ; caco_walk1_L
        dta 32  ; caco_walk2_L
        dta 32  ; caco_walk3_L
        dta 32  ; caco_shoot_L
        dta 32  ; caco_death1_L
        dta 32  ; shotgun_idle_L
        dta 32  ; shotgun_walk1_L
        dta 32  ; shotgun_walk2_L
        dta 32  ; shotgun_walk3_L
        dta 32  ; shotgun_shoot_L
        dta 32  ; shotgun_death1_L
        dta 32  ; baron_idle_L
        dta 32  ; baron_walk1_L
        dta 32  ; baron_walk2_L
        dta 32  ; baron_walk3_L
        dta 32  ; baron_shoot_L
        dta 32  ; baron_death1_L
        dta 16  ; chaingunpk
        dta 16  ; rocketpk
        dta 8   ; rocket_proj
        dta 16  ; rocketbox
        dta 32  ; zombie_death2
        dta 32  ; zombie_death3
        dta 32  ; zombie_gib1
        dta 32  ; zombie_gib2
        dta 32  ; imp_gib1
        dta 32  ; imp_gib2
        dta 32  ; shotgun_gib1
        dta 32  ; shotgun_gib2
        dta 32  ; imp_death2
        dta 32  ; imp_death3
        dta 32  ; shotgun_death2
        dta 32  ; shotgun_death3
        dta 32  ; pinky_death2
        dta 32  ; pinky_death3
        dta 32  ; caco_death2
        dta 32  ; caco_death3
        dta 32  ; baron_death2
        dta 32  ; baron_death3
        dta 16  ; barrel_exp1 (16x16)
        dta 16  ; barrel_exp2 (16x16)
        dta 16  ; barrel_exp3 (16x16)
        dta 16  ; plasmagunpk
        dta 16  ; cellspk
        dta 8   ; plasma_proj1
        dta 8   ; plasma_proj2
        dta 16  ; bfg_proj1
        dta 16  ; bfg_proj2
        dta 16  ; bfgpk
        dta 16  ; rocket1pk
        dta 16  ; armorbonus
        dta 32  ; pl_death2
        dta 32  ; pl_death3
        dta 8   ; imp_fire1
        dta 8   ; imp_fire2
        dta 32  ; pl_pain
        dta 32  ; pl_pain_L
        dta 32  ; zombie_pain
        dta 32  ; zombie_pain_L
        dta 8   ; caco_fire1
        dta 8   ; caco_fire2

; Enemy base sprite + HP tables
en_base_spr
        dta 6  ; zombie
        dta 12  ; imp
        dta 18  ; pinky
        dta 24  ; caco
        dta 30  ; shotgun
        dta 36  ; baron

en_hp_tab
        dta 3  ; zombie
        dta 5  ; imp
        dta 8  ; pinky
        dta 12  ; caco
        dta 6  ; shotgun
        dta 20  ; baron

en_speed_tab
        dta 2  ; zombie
        dta 2  ; imp
        dta 3  ; pinky (melee - must catch player)
        dta 2  ; caco
        dta 2  ; shotgun
        dta 2  ; baron

; Gib sprite lookup (indexed by enemy type, 2 frames per type)
; Death frame 2 lookup (indexed by enemy type, 0=use death1)
en_death2_spr
        dta SPR_ZOMBIE_DEATH2  ; zombie
        dta SPR_IMP_DEATH2     ; imp
        dta SPR_PINKY_DEATH2   ; pinky
        dta SPR_CACO_DEATH2    ; caco
        dta SPR_SHOTGUN_DEATH2 ; shotgun
        dta SPR_BARON_DEATH2   ; baron

; Death frame 3 lookup (indexed by enemy type, 0=use death1)
en_death3_spr
        dta SPR_ZOMBIE_DEATH3  ; zombie
        dta SPR_IMP_DEATH3     ; imp
        dta SPR_PINKY_DEATH3   ; pinky
        dta SPR_CACO_DEATH3    ; caco
        dta SPR_SHOTGUN_DEATH3 ; shotgun
        dta SPR_BARON_DEATH3   ; baron

; Gib sprite lookup (indexed by enemy type)
en_gib1_spr
        dta SPR_ZOMBIE_GIB1    ; zombie
        dta SPR_IMP_GIB1       ; imp
        dta SPR_ZOMBIE_GIB1    ; pinky (reuse zombie)
        dta SPR_ZOMBIE_GIB1    ; caco (reuse zombie)
        dta SPR_SHOTGUN_GIB1   ; shotgun
        dta SPR_ZOMBIE_GIB1    ; baron (reuse zombie)

en_gib2_spr
        dta SPR_ZOMBIE_GIB2    ; zombie
        dta SPR_IMP_GIB2       ; imp
        dta SPR_ZOMBIE_GIB2    ; pinky (reuse zombie)
        dta SPR_ZOMBIE_GIB2    ; caco (reuse zombie)
        dta SPR_SHOTGUN_GIB2   ; shotgun
        dta SPR_ZOMBIE_GIB2    ; baron (reuse zombie)

; Enemy sound lookup tables (indexed by type, $FF = no sound)
en_death_sfx
        dta SFX_PODEATH    ; zombie
        dta SFX_IMPDEATH   ; imp
        dta SFX_SGTDTH     ; pinky
        dta SFX_CACDTH     ; caco
        dta SFX_PODEATH    ; shotgun (same as zombie)
        dta SFX_BRSDTH     ; baron

; Pain sprite lookup (indexed by enemy type, R variant, add 1 for L)
en_pain_spr
        dta SPR_ZOMBIE_PAIN    ; zombie
        dta 0                  ; imp (TODO)
        dta 0                  ; pinky (TODO)
        dta 0                  ; caco (TODO)
        dta 0                  ; shotgun (TODO - same as zombie)
        dta 0                  ; baron (TODO)

en_sight_sfx
        dta SFX_POSIGHT    ; zombie
        dta SFX_IMPSIGHT   ; imp
        dta SFX_SGTSIT     ; pinky
        dta SFX_CACSIT     ; caco
        dta SFX_POSIGHT    ; shotgun (same as zombie)
        dta SFX_BRSSIT     ; baron

; Pickup type -> sprite index
pk_spr_tab
        dta 45  ; PK_HEALTH -> stimpack
        dta 47  ; PK_AMMO -> ammo_clip
        dta 44  ; PK_MEDIKIT -> medikit
        dta 48  ; PK_GREENARMOR -> greenarmor
        dta 49  ; PK_BLUEARMOR  -> bluearmor
        dta 50  ; PK_SOULSPHERE -> soulsphere
        dta 51  ; PK_KEYRED     -> keyred
        dta 52  ; PK_KEYBLUE    -> keyblue
        dta 53  ; PK_KEYYELLOW  -> keyyellow
        dta 54  ; PK_SHOTGUNPK  -> shotgunpk
        dta 55  ; PK_SHELLS     -> shells
        dta 47  ; PK_PISTOL     -> ammo_clip (temp, reuse)
        dta 102 ; PK_CHAINGUN   -> chaingunpk
        dta 103 ; PK_ROCKETL    -> rocketpk
        dta 105 ; PK_ROCKETBOX  -> rocketbox
        dta SPR_PLASMAGUNPK  ; PK_PLASMAGUN
        dta SPR_CELLSPK      ; PK_CELLS
        dta SPR_BFGPK        ; PK_BFG
        dta SPR_ROCKET1PK   ; PK_ROCKET1
        dta 46              ; PK_HEALTHBONUS -> health_bonus
        dta SPR_ARMORBONUS  ; PK_ARMORBONUS

; Tile indices
TILE_EMPTY                equ   0  ; offset $0000
TILE_WALL                 equ   1  ; offset $0100
TILE_FLOOR                equ   2  ; offset $0200
TILE_CEILING              equ   3  ; offset $0300
TILE_DOOR                 equ   4  ; offset $0400
TILE_SKY                  equ   5  ; offset $0500
TILE_DARKBG               equ   6  ; offset $0600
TILE_TECHWALL             equ   7  ; offset $0700
TILE_METALWALL            equ   8  ; offset $0800
TILE_SUPPORT              equ   9  ; offset $0900
TILE_STONEWALL            equ  10  ; offset $0A00
TILE_RESERVED_11          equ  11  ; offset $0B00
TILE_RESERVED_12          equ  12  ; offset $0C00
TILE_RESERVED_13          equ  13  ; offset $0D00
TILE_RESERVED_14          equ  14  ; offset $0E00
TILE_RESERVED_15          equ  15  ; offset $0F00
TILESHEET_SIZE           equ $1000
